//Actions
export const ADD_BASE_SIZE = "ADD_BASE_SIZE";
export const ADD_PIZZA_TO_ORDER = "ADD_PIZZA_TO_ORDER";
export const REMOVE_PIZZA_FROM_ORDER = "REMOVE_PIZZA_FROM_ORDER";
export const TOGGLE_PIZZA_BUILDER = "TOGGLE_PIZZA_BUILDER";